language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

deploy:
  provider: releases
  api_key:
    secure: aBYrIqfhXWExsXTgbo48jZC4iX3BuwNqixfLCWlfozY/VElMyiz4GvJnon1LYYYqhjC97zUc80P91UMcVELCKmI/9qhcINTs/mDXc8EpgLI4c4npDLbC7ZQ3oAJ5FwZczfQPzRwSIpKIMNGugpZc7tITZ/RL6lrBGRLfZUK9qco=
  file_glob: true
  file: air-util/target/*.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    jdk: oraclejdk8
    repo: LonelyStorm/air
