language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
    - secure: "C487oZ9IG4zlJa2UskW1Qfppejj8j35+eTi3mHr/0oC9czM/9ceS6vOJoeOhehwDGgJ8AA/9USn+srYJAx+9qeWvomLi5zGt422Ob2lI1L/O7snzWJJw5FRPFEC0KX+YuAaC2VsThUxy7SZsffDEIfBB5AcGL95Pl+8sfSQVn7I="

before_install:
  - openssl enc -aes-256-cbc -d -a -in private.gpg.enc -out private.gpg -K $OPENSSL_KEY -iv $OPENSSL_IV -S $OPENSSL_SALT
  - openssl enc -aes-256-cbc -d -a -in public.gpg.enc -out public.gpg -K $OPENSSL_KEY -iv $OPENSSL_IV -S $OPENSSL_SALT

deploy:
  provider: releases
  api_key:
    secure: aBYrIqfhXWExsXTgbo48jZC4iX3BuwNqixfLCWlfozY/VElMyiz4GvJnon1LYYYqhjC97zUc80P91UMcVELCKmI/9qhcINTs/mDXc8EpgLI4c4npDLbC7ZQ3oAJ5FwZczfQPzRwSIpKIMNGugpZc7tITZ/RL6lrBGRLfZUK9qco=
  file_glob: true
  file: ./air-util/target/*.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    jdk: oraclejdk8
    repo: LonelyStorm/air

after_success:
  - test $TRAVIS_SECURE_ENV_VARS == "true" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_JDK_VERSION == "oraclejdk8" && javac ./Setup.java && java Setup && mvn deploy -Prelease
